theme: jekyll-theme-hacker

title: API Igniter Docs

include:
  - docs

exclude:
  - .github/workflows/pest.yml
  - src
  - stubs
  - tests
  - vendor
  - workbench
  - .editorconfig
  - .gitattributes
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - composer.lock
  - _config.yml
  - tests
  - favicon.png
  - phpunit.xml
  - setup-workbench.php
  - stubs
  - composer.json
  - testbench.yaml
